KAN-206 - Create shared/reusable workflow
AstrumU/shared-workflows pull request #1
Opened 2022-11-09 15:21 UTC by andriiholubenko

2022-11-11 11:34 UTC, vtereshyn requested changes

2022-11-11 11:34 UTC, vtereshyn commented on .github/workflows/build.yml
> +      builded: ${{ steps.build.outputs.builded }}
why do you need this?

2022-11-11 11:34 UTC, vtereshyn commented on .github/workflows/build.yml
> +        required: true
probably should be `false`

2022-11-11 11:34 UTC, vtereshyn commented on .github/workflows/build.yml
> +      natToken:
```suggestion
      NODE_AUTH_TOKEN:
```

2022-11-11 11:34 UTC, vtereshyn commented on .github/workflows/build.yml
> +        required: false
should be true and let's put v1 here

2022-11-11 11:34 UTC, vtereshyn commented on .github/workflows/build.yml
> +        required: false
each repo that's gonna use this `shared-workflow` should pass worn cache version

2022-11-11 11:35 UTC, vtereshyn commented on .github/workflows/tests.yml
> +          pnpmVersion: ${{inputs.pnpmVersion}}
```suggestion
          nodeVersion: ${{ inputs.nodeVersion }}
          packageManager: ${{ inputs.packageManager }}
          cacheVersion: ${{ inputs.cacheVersion }}
          pnpmVersion: ${{ inputs.pnpmVersion }}
```

2022-11-11 11:35 UTC, vtereshyn commented on .github/workflows/tests.yml
> +          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
```suggestion
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
```

why are we using `NODE_AUTH_TOKEN` here but not `natToken`?

2022-11-11 11:48 UTC, vtereshyn commented on .github/workflows/ci.yml
> +          path: ./*
should cache only `dist` folders

2022-11-14 08:11 UTC, vtereshyn commented on .github/workflows/build.yml
> +        default: 7.13.3
we agreed to put `7` here

2022-11-14 15:59 UTC, yevhenii-r requested changes
lets configure separate job in separate file

2022-11-15 13:39 UTC, yevhenii-r approved these changes

2022-11-15 14:08 UTC, merged