feat: KAN-319 Create GitHub JavaScript Actions for Slack notifications script
AstrumU/shared-workflows pull request #30
Opened 2023-02-27 10:52 UTC by andriiholubenko

2023-03-03 12:32 UTC, vtereshyn requested changes

2023-03-03 12:32 UTC, vtereshyn commented on .github/actions/slack-notify/src/index.js
> +function date_diff_func(start, end) {
in JS we should name functions using camel case – `dateDiffFunc`. The function name should describe what's happening here. `date_diff_func` doesn't describe that

2023-03-03 12:32 UTC, vtereshyn commented on .github/actions/slack-notify/src/index.js
> +  var duration = end - start;
please, change `var` to `const` or `let`.

2023-03-03 12:32 UTC, vtereshyn commented on .github/actions/slack-notify/action.yml
> +  using: "node16"
why not 16+?

2023-03-03 12:32 UTC, vtereshyn commented on .github/actions/slack-notify/src/index.js
> +}
```suggestion
}

```

2023-03-03 12:32 UTC, vtereshyn commented on .github/actions/slack-notify/src/index.js
> +function status_icon_func(s) {
```suggestion
function getStatusIcon(s) {
```

2023-03-03 12:32 UTC, vtereshyn commented on .github/actions/slack-notify/src/index.js
> +  }
let's change this function and `status_text_func` to object mapping. Example:

```
const STATUS_TO_ICON = {
	failure: "\u20e0",
	success: "\u2705"
}
```

2023-03-03 12:32 UTC, vtereshyn commented on .github/actions/slack-notify/src/index.js
> +    var is_wf_failure = false;
const or let

2023-03-03 12:32 UTC, vtereshyn commented on .github/actions/slack-notify/src/index.js
> +    var slack_msg = {
please, do not use `var`

2023-03-03 16:44 UTC, andriiholubenko commented on .github/actions/slack-notify/action.yml
> +  using: "node16"
<img width="642" alt="image" src="https://user-images.githubusercontent.com/103764137/222777408-0c24d3e3-f986-4ea7-90e0-1b76a80b5612.png">

Currently only Node12 and Node16 are available

2023-03-06 13:11 UTC, vtereshyn requested changes

2023-03-06 13:11 UTC, vtereshyn commented on .github/actions/slack-notify/package-lock.json
> +{
why are you using `npm` here?

2023-03-06 13:11 UTC, vtereshyn commented on .github/actions/slack-notify/package.json
> +    "@actions/github": "^5.1.1"
```suggestion
    "@actions/core": "1.10.0",
    "@actions/github": "5.1.1"
```

2023-03-06 13:11 UTC, vtereshyn commented on .github/actions/slack-notify/src/index.js
> +  return (
please, add spaces

2023-03-06 13:11 UTC, vtereshyn commented on .github/actions/slack-notify/src/index.js
> +  return "\u20e0";
```suggestion
  return statusIcons[s] || "\u20e0";
```

2023-03-06 13:11 UTC, vtereshyn commented on .github/actions/slack-notify/src/index.js
> +  return "\u20e0";
same as above

2023-03-07 16:13 UTC, vtereshyn commented on .github/actions/slack-notify/src/index.js
> +  const formatFunc = function (v, text, check) {
please, define this function outside. also there is no need to assign function to variable:

```
function formatFunc (v, text, check) {
....
....
```

2023-03-07 16:15 UTC, vtereshyn commented on .github/actions/slack-notify/src/index.js
> +      wfRun.data.jobs_url + "?per_page=100"
```suggestion
      `${wfRun.data.jobs_url}?per_page=100`
```

2023-03-07 16:16 UTC, vtereshyn commented on .github/actions/slack-notify/src/index.js
> +      fields,
```suggestion
      fields
```

2023-03-09 11:42 UTC, vtereshyn commented on .github/actions/slack-notify/src/index.js
> +  }
```suggestion
  if (time <= 0 && check) {
    return "";
  }

    return time + timeType;

```

2023-03-09 11:42 UTC, vtereshyn commented on .github/actions/slack-notify/src/index.js
> +    return "";
what is this format about? it returns an empty string. do you need this?

2023-03-09 15:36 UTC, andriiholubenko commented on .github/actions/slack-notify/src/index.js
> +    return "";
Returning an empty value in the "formatTime" function is necessary in order not to show zero values for  - days, minutes, hours in "dateDifference" function. At the same time we want to show zero for seconds if needed.

2023-03-10 10:31 UTC, vtereshyn approved these changes

2023-03-10 15:22 UTC, merged